name: Reusable CI-CD (Build on GitHub, Deploy on Self-hosted)

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      app_name:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:

  build-and-push:
    name: Build & Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.image_name }} .

      - name: Push Docker Image
        run: |
          docker push ${{ inputs.image_name }}

  deploy:
    name: Deploy to K3s
    runs-on: [self-hosted, Linux, X64]
    needs: build-and-push

    steps:
      - name: Checkout application code
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment ${{ inputs.app_name }}
